# MATH OPERATIONS  IN  NUMPY:

NumPy is a Python library used for numerical calculations. Its main object is an array, which allows mathematical operations to be performed quickly on many values at once.

In [2]:
import numpy as np



2. Element-Wise Arithmetic Operations
In NumPy, basic arithmetic operations are usually performed element by element.

Addition

In [15]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
# [11 22 33]

print(np.add(a, b))
# [11 22 33]

[11 22 33]
[11 22 33]


##subtractions :

In [16]:
print(a - b)
# [9 18 27] 

print(np.subtract(a, b))
# [9 18 27]

[ 9 18 27]
[ 9 18 27]


MULTIPLICATIONS :


In [19]:
print(a * b)

print(np.multiply(a, b))

[10 40 90]
[10 40 90]


In [21]:
arr1= np.array([32,30,49])
arr2= np.array([12,15,20])
np.mod(arr1,arr2)

array([8, 0, 9])

In [9]:
arr= np.array((32,30,49))
arr

array([32, 30, 49])

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### **2[i] .inbuild  operations  of an array:**

used to perform the mathamatical operations like 

1. max():
   max  will help user to find the maximum value from the array
2. min()
3. mean()  # avg
4. median() # mid
5. mod()
6. variance()
7. std()
8. more things ...etc

2.min()
it will return the minimum value from the array
**syntax:**    np.min(variable)

In [23]:
arr1= np.array([32,30,49])
arr2= np.array([12,15,20])
np.min(arr1)

30

1.max():
max  will help user to find the maximum value from the array

In [24]:
arr1= np.array([32,30,49])
np. max(arr1)

49

In [26]:
# Example array for all operations
arr = np.array([10, 20, 30, 40, 50])

# 1. max() - Find maximum value
print("1. max():")
print(f"   Array: {arr}")
print(f"   Maximum value: {np.max(arr)}")
print()

# 2. min() - Find minimum value
print("2. min():")
print(f"   Minimum value: {np.min(arr)}")
print()

# 3. mean() - Calculate average
print("3. mean():")
print(f"   Average (mean): {np.mean(arr)}")
print()

# 4. median() - Find middle value
print("4. median():")
print(f"   Median value: {np.median(arr)}")
print()

# 5. mod() - Modulo operation
print("5. mod():")
arr2 = np.array([12, 15, 20])
divisor = 5
print(f"   Array: {arr2}")
print(f"   Modulo {divisor}: {np.mod(arr2, divisor)}")
print()

# 6. variance()  - Measure of spread
print("6. variance():")
print(f"   Variance: {np.var(arr)}")
print()

# 7. std() - Standard deviation
print("7. std():")
print(f"   Standard Deviation: {np.std(arr)}")

1. max():
   Array: [10 20 30 40 50]
   Maximum value: 50

2. min():
   Minimum value: 10

3. mean():
   Average (mean): 30.0

4. median():
   Median value: 30.0

5. mod():
   Array: [12 15 20]
   Modulo 5: [2 0 0]

6. variance():
   Variance: 200.0

7. std():
   Standard Deviation: 14.142135623730951


### **Additional Array Operations:**

* **abs()** - Convert all negative values to positive
  - **syntax:** `np.abs(variable)`
  
* **size()** - Find the number of elements in array
  - **syntax:** `np.size(variable)`
  
* **sum()** - Calculate sum of all array elements
  - **syntax:** `np.sum(variable)`

In [27]:
# Example array with negative values
arr_with_neg = np.array([-5, 10, -15, 20, -25])

# 1. abs() - Convert negative to positive
print("1. abs():")
print(f"   Original array: {arr_with_neg}")
print(f"   Absolute values: {np.abs(arr_with_neg)}")
print()

# 2. size() - Find number of elements
print("2. size():")
arr = np.array([10, 20, 30, 40, 50])
print(f"   Array: {arr}")
print(f"   Number of elements: {np.size(arr)}")
print()

# 3. sum() - Calculate sum of all elements
print("3. sum():")
print(f"   Array: {arr}")
print(f"   Sum of all elements: {np.sum(arr)}")
print(f"   Total: 10 + 20 + 30 + 40 + 50 = {np.sum(arr)}")

1. abs():
   Original array: [ -5  10 -15  20 -25]
   Absolute values: [ 5 10 15 20 25]

2. size():
   Array: [10 20 30 40 50]
   Number of elements: 5

3. sum():
   Array: [10 20 30 40 50]
   Sum of all elements: 150
   Total: 10 + 20 + 30 + 40 + 50 = 150


## **Complete Summary of NumPy Array Operations**

| Operation | Description | Syntax | Example |
|-----------|-------------|--------|---------|
| **max()** | Find maximum value | `np.max(arr)` | `np.max([10, 20, 50])` → 50 |
| **min()** | Find minimum value | `np.min(arr)` | `np.min([10, 20, 50])` → 10 |
| **mean()** | Calculate average | `np.mean(arr)` | `np.mean([10, 20, 50])` → 26.67 |
| **median()** | Find middle value | `np.median(arr)` | `np.median([10, 20, 50])` → 20 |
| **abs()** | Convert to absolute (positive) | `np.abs(arr)` | `np.abs([-5, 10])` → [5, 10] |
| **sum()** | Sum all elements | `np.sum(arr)` | `np.sum([10, 20, 50])` → 80 |
| **size()** | Count elements | `np.size(arr)` | `np.size([10, 20, 50])` → 3 |
| **mod()** | Modulo (remainder) | `np.mod(arr, div)` | `np.mod([12, 15], 5)` → [2, 0] |
| **variance()** | Measure of spread | `np.var(arr)` | `np.var([10, 20, 50])` → 400 |
| **std()** | Standard deviation | `np.std(arr)` | `np.std([10, 20, 50])` → 20 |