In [1]:
import numpy as np

In [5]:
arr1= np.array([32,30,49])
arr1[-1]



49

indexing


In [40]:
arr2= np.array([[1,2,3,4,5],
[1,4,6,7,7],
[1,2,3,4,5,]])
arr2[1,2]

### 02 element accesing the  array 

arr2[0,2,] # 

3

slicing :



In [29]:
arr3= np.array([
[1,2,3,4,5],
[1,4,6,7,7],
[1,2,3,4,5,]
])


##slicing 
#**2D**-========>..`arr[row slicin: column slicing]`

arr3[1:6:4, 2:4:4]



arr3[4:2-1:-1,]

array([[1, 2, 3, 4, 5]])

In [ ]:
a= "i am learning numpy and pandas"
a[5:13] # learning
a[14:19]
a[:4]

a[:24-1:-1] #'sadnap'
a[29:0:-1]  #'sadnap dna ypmun gninrael ma '
a[5:12:2]  #'lann'
a[]

'lann'

1D SLICING ACCES :


In [ ]:
b= np.array([1,9,5,69,16,67])
#1,5,16  expected out 
b[0:5:2]    ##array([ 1,  5, 16])

#67,69,9

b[-1:0:-2]    # array([67, 69,  9])   

#another type   b[5:0:-2]

array([67, 69,  9])

2D ACCESSING SLICING :'


In [ ]:
arr4= np.array([
[5,48,43,4],
[40,2,34,27],
[38,24,20,19]
])

###[2,27,24,19]
arr4[1:3,1:4:2]    ###array([[ 2, 27],[24, 19]])

array([[ 2, 27],
       [24, 19]])

In [78]:
arr4=np.array([
    
    [[1,2,3,4],[2,4,5,6,]],
    [[4,3,6,8],[0,4,2,9]]]
)

arr4.ndim   ### 3     layer , rows , columns 



arr4[:,:,:2]
arr4[:,1:2,1:4:2

]


array([[[4, 6]],

       [[4, 9]]])